// entrypoints/admin/src/pages/dataSharePlan/PartnerFind.tsx
import { Avatar, Button, Flex, Pagination, Space, Spin, Table, TableColumnsType, Tooltip, Typography } from "antd";
const { Text } = Typography;

import { DataSharePartnerApi } from "@/common/api";
import { GithubApi } from "@/common/api/github";
import { COMMENT_PAGE_SIZE, DEFAULT_DATA_REPO, DEFAULT_REPO_TYPE } from "@/common/config";
import { SearchDataSharePartnerBO } from "@/common/data/bo/searchDataSharePartnerBO";
import { DataSharePartner } from "@/common/data/domain/dataSharePartner";
import { dateToStr } from "@/common/utils";
import { Icon } from "@iconify/react";
import { TableRowSelection } from "antd/lib/table/interface";
import dayjs from "dayjs";
import { useShallow } from "zustand/shallow";
import { PageInfo } from "../../data/PageInfo";
import { Owner, RepositoryData } from "../../data/RepositoryData";
import useAuthStore from "../../store/AuthStore";
import styles from "./PartnerFind.module.css";

export type PartnerFindProps = {

};
const PartnerFind: React.FC<PartnerFindProps> = ({ }) => {

    const [loading, setLoading] = useState<boolean>(false);
    const [dataSource, setDataSource] = useState<RepositoryData[]>([]);
    const [refresh, setRefresh] = useState(false);
    const [searchParam, setSearchParam] = useState({
        first: COMMENT_PAGE_SIZE,
        after: null,
        last: null,
        before: null,
        repo: DEFAULT_DATA_REPO,
    })
    const [selectedRowKeys, setSelectedRowKeys] = useState<React.Key[]>([]);
    const [idObjectMap, setIdObjectMap] = useState<Map<string, RepositoryData>>(new Map());
    const [dataSharePartnerMap, setDataSharePartnerMap] = useState<Map<string, void>>(new Map());
    const [total, setTotal] = useState(0);
    const [currentPage, setCurrentPage] = useState(1);
    const [pageSize, setPageSize] = useState(COMMENT_PAGE_SIZE);
    const [pageInfo, setPageInfo] = useState<PageInfo>();
    const topRef = useRef();
    const [addLoading, setAddLoading] = useState(false);
    const [username] = useAuthStore(useShallow(((state) => [
        state.username,
    ])));

    const genState = (id: string) => {
        if (!idObjectMap.has(id)) {
            return null;
        }
        const item = idObjectMap.get(id);
        if (item.owner.login == username) {
            return <>
                <Tooltip title="不能添加自己">
                    <Icon icon="icon-park-outline:invalid-files" width="20" height="20" />
                </Tooltip>
            </>
        } else if (item.name != DEFAULT_DATA_REPO) {
            return <>
                <Tooltip title="仓库名不符合条件">
                    <Icon icon="icon-park-outline:invalid-files" width="20" height="20" />
                </Tooltip>
            </>
        } else {
            if (dataSharePartnerMap.has(item.owner.login)) {
                return <>
                    <Tooltip title="已添加到伙伴列表">
                        <Icon className={styles.partnerExists} icon="carbon:partnership" width="20" height="20" />
                    </Tooltip>
                </>
            } else {
                return <>
                    <Tooltip title="可添加到伙伴列表">
                        <Icon className={styles.partnerAdd} icon="basil:add-outline" width="20" height="20" />
                    </Tooltip>
                </>
            }
        }
    }

    const columns: TableColumnsType<RepositoryData> = [
        {
            title: '状态',
            dataIndex: 'id',
            render: (value: string) => <Flex>{
                genState(value)
            }
            </Flex>,
            minWidth: 60,
        },
        {
            title: '头像',
            dataIndex: 'owner',
            render: (value: Owner) => <Avatar src={value.avatarUrl} />,
        },
        {
            title: '用户名',
            dataIndex: 'owner',
            render: (value: Owner) => <Text>{value.login}</Text>,
            minWidth: 100,
        },
        {
            title: '仓库名',
            dataIndex: 'name',
            render: (value: string) => <Text>{value}</Text>,
        },
        {
            title: '星数',
            dataIndex: 'stargazerCount',
            render: (value: number) => <Text>{value}</Text>,
        },
        {
            title: '最近更新时间',
            dataIndex: 'updatedAt',
            render: (value: string) => <Text>{dateToStr(dayjs(value),"YYYY-MM-DD")}</Text>,
            minWidth: 100,
        },
        {
            title: '创建时间',
            dataIndex: 'createdAt',
            render: (value: string) => <Text>{dateToStr(dayjs(value),"YYYY-MM-DD")}</Text>,
            minWidth: 100,
        },
    ]

    const fetchData = () => {
        (async () => {
            scrollToTop();
            setLoading(true);
            let result = await GithubApi.queryRepository(searchParam);
            const { nodes } = result.search;
            const map = new Map<string, RepositoryData>();
            nodes.map((item, index) => {
                map.set(item.id, item);
            })
            setIdObjectMap(map);
            if (nodes.length > 0) {
                //获取数据共享计划伙伴
                const searchDataSharePartnerParam = new SearchDataSharePartnerBO();
                searchDataSharePartnerParam.usernameList = nodes.flatMap(item => item.owner.login);
                searchDataSharePartnerParam.orderByColumn = "updateDatetime";
                searchDataSharePartnerParam.orderBy = "DESC";
                let partnerResult = await DataSharePartnerApi.searchDataSharePartner(searchDataSharePartnerParam);
                let partnerResultItems = partnerResult.items;
                const dataSharePartnerMap = new Map();
                for (let i = 0; i < partnerResultItems.length; i++) {
                    let item = partnerResultItems[i];
                    dataSharePartnerMap.set(item.username, null);
                }
                setDataSharePartnerMap(dataSharePartnerMap);
            }
            setDataSource(nodes);
            setTotal(result.search.repositoryCount);
            setPageInfo(result.search.pageInfo);
            setLoading(false);
        })();
    };

    useEffect(() => {
        fetchData();
    }, [])

    useEffect(fetchData, [
        searchParam,
        currentPage,
        pageSize,
        refresh,
    ]);

    const onSelectChange = (newSelectedRowKeys: React.Key[]) => {
        setSelectedRowKeys(newSelectedRowKeys);
    };

    const rowSelection: TableRowSelection<any> = {
        selectedRowKeys,
        onChange: onSelectChange,
        getCheckboxProps: (record) => ({
            disabled: record.owner.login === username ||
                record.name != DEFAULT_DATA_REPO ||
                dataSharePartnerMap.has(record.owner.login),
        }),
    };

    const onPageChange = (page: number, pageSize: number) => {
        if (page > currentPage) {
            searchParam.first = pageSize;
            searchParam.last = null;
            searchParam.after = pageInfo ? pageInfo.endCursor : null;
            searchParam.before = null;
            setCurrentPage(currentPage + 1);
        } else {
            searchParam.first = null;
            searchParam.last = pageSize;
            searchParam.after = null;
            searchParam.before = pageInfo ? pageInfo.startCursor : null;
            setCurrentPage(currentPage - 1);
        }
        setPageSize(pageSize);
        setSearchParam(Object.assign({}, searchParam));
    }

    const scrollToTop = () => {
        topRef.current.scrollIntoView();
    }

    const onAdd = async () => {
        setAddLoading(true);
        try {
            const selectedRows = dataSource.filter(item => {
                return selectedRowKeys.find(key => key == item.id);
            });
            const entityList = [];
            for (let i = 0; i < selectedRows.length; i++) {
                const item = selectedRows[i];
                const entity = new DataSharePartner();
                entity.username = item.owner.login;
                entity.reponame = item.name;
                entity.repoType = DEFAULT_REPO_TYPE;
                entityList.push(entity);
            }
            await DataSharePartnerApi.dataSharePartnerBatchAddOrUpdate(entityList);
        } finally {
            setAddLoading(false);
        }
        setRefresh(!refresh);
    }

    const hasSelected = selectedRowKeys.length > 0;

    return <>
        <Spin spinning={loading}>
            <Flex vertical gap={10}>
                <Flex justify="end">
                    <Button type="primary" loading={addLoading} disabled={!hasSelected} onClick={onAdd}>添加</Button>
                </Flex>
                <Flex ref={topRef} vertical gap={10}>
                    <Flex justify="end">
                        <Pagination simple current={currentPage} total={total} pageSize={pageSize} onChange={onPageChange} />
                    </Flex>
                    <Space size="small" direction="vertical">
                        <Table<RepositoryData>
                            rowKey={(record) => {
                                return record.id;
                            }}
                            columns={columns}
                            dataSource={dataSource}
                            pagination={false}
                            rowSelection={rowSelection}
                        />
                        <Flex justify="end">
                            <Pagination simple current={currentPage} total={total} pageSize={pageSize} onChange={onPageChange} />
                        </Flex>
                    </Space>
                </Flex>
            </Flex>
        </Spin>
    </>
}
export default PartnerFind;

// src/sidepanel/views/dataSharePlan/PartnerFind.vue
<template>
    <div v-loading="loading">
        <div class="menu">
            <el-popconfirm title="确认添加选中的数据？" @confirm="onBatchAdd" confirm-button-text="确定" cancel-button-text="取消">
                <template #reference>
                    <el-button type="primary">批量添加</el-button>
                </template>
            </el-popconfirm>
        </div>
        <el-table ref="tableRef" :data="tableData" :row-class-name="tableRowClassName">
            <el-table-column type="selection" width="55" :selectable="repoNameSelectable" />
            <el-table-column label="状态" width="60">
                <template #default="scope">
                    <div v-if="scope.row.owner.login == myInfo.login">
                        <el-tooltip content="不能添加自己">
                            <Icon icon="icon-park-outline:invalid-files" width="20" height="20" />
                        </el-tooltip>
                    </div>
                    <div v-else>
                        <div v-if="scope.row.name == DEFAULT_DATA_REPO">
                            <el-tooltip v-if="dataSharePartnerMap.has(scope.row.owner.login)" content="已添加到伙伴列表">
                                <Icon class="partnerExists" icon="carbon:partnership" width="20" height="20" />
                            </el-tooltip>
                            <el-tooltip v-else content="可添加到伙伴列表">
                                <Icon class="partnerAdd" icon="basil:add-outline" width="20" height="20" />
                            </el-tooltip>
                        </div>
                        <el-tooltip v-else content="仓库名不符合条件">
                            <Icon icon="icon-park-outline:invalid-files" width="20" height="20" />
                        </el-tooltip>
                    </div>
                </template>
            </el-table-column>
            <el-table-column label="头像" width="70">
                <template #default="scope">
                    <el-avatar :src="scope.row.owner.avatarUrl" />
                </template>
            </el-table-column>
            <el-table-column label="用户名" width="120" show-overflow-tooltip>
                <template #default="scope">
                    <el-text line-clamp="1">
                        {{ scope.row.owner.login }}
                    </el-text>
                </template>
            </el-table-column>
            <el-table-column label="仓库名" show-overflow-tooltip>
                <template #default="scope">
                    <el-text line-clamp="1">
                        {{ scope.row.name }}
                    </el-text>
                </template>
            </el-table-column>
            <el-table-column label="星数" width="60" show-overflow-tooltip>
                <template #default="scope">
                    <el-text line-clamp="1">
                        {{ scope.row.stargazerCount }}
                    </el-text>
                </template>
            </el-table-column>
            <el-table-column label="最近更新时间" width="120" show-overflow-tooltip>
                <template #default="scope">
                    <el-text line-clamp="1">
                        {{ datetimeFormat(scope.row.updatedAt) }}
                    </el-text>
                </template>
            </el-table-column>
            <el-table-column label="创建时间" width="120" show-overflow-tooltip>
                <template #default="scope">
                    <el-text line-clamp="1">
                        {{ datetimeFormat(scope.row.createdAt) }}
                    </el-text>
                </template>
            </el-table-column>
        </el-table>
        <el-pagination v-model:current-page="currentPage" v-model:page-size="pageSize"
            :page-sizes="[10, 20, 50, 100, 200, 500, 1000]" :small="small" :disabled="disabled" :background="background"
            layout="total, sizes, prev,next" :total="total" @size-change="handleSizeChange" @prev-click="onPagePrevious"
            @next-click="onPageNext" />
    </div>
</template>
<script lang="ts" setup>
import { ref, onMounted, reactive, toRaw, computed } from 'vue'
import { MAX_RECORD_COUNT } from "../../../common";
import { DEFAULT_DATA_REPO, COMMENT_PAGE_SIZE, DEFAULT_REPO_TYPE } from "../../../common/config"
import { UserApi } from "../../../common/api";
import { GithubApi, EXCEPTION } from "../../../common/api/github";
import dayjs from "dayjs";
import { SearchDataSharePartnerBO } from "../../../common/data/bo/searchDataSharePartnerBO";
import { DataSharePartnerApi } from "../../../common/api";
import { ElTable, ElMessage } from "element-plus";
import { DataSharePartner } from "../../../common/data/domain/dataSharePartner";
import { errorLog } from "../../../common/log"
import { Icon } from '@iconify/vue';

const emits = defineEmits(["batchAddSuccess"]);

const datetimeFormat = computed(() => {
    return function (value: string) {
        return dayjs(value).isValid() ? dayjs(value).format("YYYY-MM-DD") : "-";
    };
});

const currentPage = ref(1);
const loading = ref(false);
const pageSize = ref(COMMENT_PAGE_SIZE);
const total = ref(0);
const tableData = ref([]);
const background = ref(false);
const disabled = ref(false);
const tableRef = ref<InstanceType<typeof ElTable>>()

const repoNameSelectable = (row: any, index: number) => {
    return row.name == DEFAULT_DATA_REPO && !(row.owner.login == myInfo.value.login) && !dataSharePartnerMap.value.has(row.owner.login);
}

const tableRowClassName = ({
    row,
    rowIndex,
}) => {
    if (row.name == DEFAULT_DATA_REPO && !(row.owner.login == myInfo.value.login) && !dataSharePartnerMap.value.has(row.owner.login)) {
        return ''
    } else {
        return 'disabled'
    }
}

const searchParam = reactive({
    first: COMMENT_PAGE_SIZE,
    after: null,
    last: null,
    before: null,
    repo: DEFAULT_DATA_REPO,
})

const pageInfo = reactive({
    endCursor: null,
    hasNextPage: null,
    hasPreviousPage: null,
    startCursor: null,
});

const dataSharePartnerMap = ref(new Map());

const myInfo = ref();

const search = async () => {
    loading.value = true;
    let param = getSearchParam();
    try {
        let result = await GithubApi.queryRepository(param);
        total.value = result.search.repositoryCount;
        tableData.value = result.search.nodes;
        const { startCursor, endCursor, hasNextPage, hasPreviousPage, } = result.search.pageInfo;
        pageInfo.startCursor = startCursor;
        pageInfo.endCursor = endCursor;
        pageInfo.hasNextPage = hasNextPage;
        pageInfo.hasPreviousPage = hasPreviousPage;
        if (tableData.value.length > 0) {
            //获取数据共享计划伙伴
            let searchParam = new SearchDataSharePartnerBO();
            searchParam.pageNum = 1;
            searchParam.pageSize = MAX_RECORD_COUNT;
            searchParam.usernameList = tableData.value.flatMap(item => item.owner.login);
            searchParam.orderByColumn = "updateDatetime";
            searchParam.orderBy = "DESC";
            let partnerResult = await DataSharePartnerApi.searchDataSharePartner(searchParam);
            let partnerResultItems = partnerResult.items;
            dataSharePartnerMap.value.clear();
            for (let i = 0; i < partnerResultItems.length; i++) {
                let item = partnerResultItems[i];
                dataSharePartnerMap.value.set(item.username, null);
            }
        }
    } catch (e) {
        if (e == EXCEPTION.NO_LOGIN) {
            ElMessage({
                message: '需要登录GitHub',
                type: 'warning',
            })
        } else {
            ElMessage({
                message: '查询失败',
                type: 'error',
            })
            throw e;
        }
    } finally {
        loading.value = false;
    }
}

const onPageNext = () => {
    if (pageInfo.hasNextPage) {
        searchParam.first = pageSize.value;
        searchParam.last = null;
        searchParam.after = toRaw(pageInfo).endCursor;
        searchParam.before = null;
        search();
    }
}

const onPagePrevious = () => {
    if (pageInfo.hasPreviousPage) {
        searchParam.first = null;
        searchParam.last = pageSize.value;
        searchParam.after = null;
        searchParam.before = toRaw(pageInfo).startCursor;
        search();
    }
}

const getSearchParam = () => {
    return toRaw(searchParam);
}

const resetParam = () => {
    searchParam.first = pageSize.value;
    searchParam.after = null;
    searchParam.last = null;
    searchParam.before = null;
    searchParam.repo = DEFAULT_DATA_REPO;
}

const reset = () => {
    resetParam();
    search();
}

onMounted(async () => {
    myInfo.value = await UserApi.userGet();
    search();
});

const handleSizeChange = (val: number) => {
    reset();
};

const onBatchAdd = async () => {
    let selectedRows = tableRef.value.getSelectionRows();
    if (selectedRows.length > 0) {
        try {
            const entityList = [];
            for (let i = 0; i < selectedRows.length; i++) {
                const item = selectedRows[i];
                const entity = new DataSharePartner();
                entity.username = item.owner.login;
                entity.reponame = item.name;
                entity.repoType = DEFAULT_REPO_TYPE;
                entityList.push(entity);
            }
            await DataSharePartnerApi.dataSharePartnerBatchAddOrUpdate(entityList);
            emits('batchAddSuccess')
            ElMessage({
                message: `伙伴名单添加成功,共${selectedRows.length}条`,
                type: 'success',
            });
            search();
        } catch (e) {
            errorLog(e);
            ElMessage({
                message: '添加伙伴失败',
                type: 'error',
            })
        }
    } else {
        ElMessage({
            message: '请选择需要添加的伙伴',
            type: 'warning',
        })
    }
}

</script>
<style lang="scss" scoped>
.menu {
    display: flex;
    justify-content: right;
}

.partnerExists {
    color: var(--el-color-success);
}

.partnerAdd {
    color: var(--el-color-primary);
}
</style>

<style lang="scss">
.el-table .disabled {
    --el-table-tr-bg-color: rgba(0, 0, 0, .02);
}
</style>
